fix `tld restore`

diff --git a/source/games b/source/games
--- a/source/games
+++ b/source/games
@@ -15,7 +15,7 @@ most_recent() {
   if command -v gls >/dev/null 2>&1; then
     ls=gls
   fi
-  $ls -1t --color=never sandbox* | head -1
+  $ls -1t --color=never | head -1
 }
 
 tld() {
@@ -40,11 +40,11 @@ tld() {
       bd="$SYNC_DIR/tld-backups"
       cd "$bd"
       if [ -z "$2" ]; then
-        savefile=$(most_recent)
+        savefile="$(most_recent)"
       else
         savefile="$2"
       fi
-      cd "$bd/$savefile" || { echo "missing save file directory to restore: $bd/$savefile" >&2; exit 2; }
+      cd "$bd/$savefile" || { echo "missing save file directory to restore: $bd/$savefile" >&2; return 2; }
       version=$(most_recent)
       tld
       cp -v "$bd/$savefile/$version" "$savefile"
